import type { Metadata } from "next";

import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer"
import "bootstrap-icons/font/bootstrap-icons.css";
import { Poppins } from "next/font/google";
import {Montserrat} from "next/font/google";


const poppins= Poppins ({subsets:["latin"], weight:["400","700"]});
const montserrat= Montserrat ({subsets:["latin"], weight:["400","700"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className} >
        <Header font={poppins}/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
